/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConexionMySql;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Consecutivos extends javax.swing.JFrame {
    DefaultComboBoxModel modeloVerificar;
    DefaultTableModel modelo;
    ArrayList<Integer> arrayListExpedientes = new ArrayList<Integer>();
    ArrayList<Integer> arrayListInstrumentos = new ArrayList<Integer>();


    public void PropiedadTabla()
    {
        jNoEncontrados.setRowHeight(30);
        modelo = new DefaultTableModel()
        {
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        modelo.setColumnIdentifiers(new Object[]{"Números no encontrados"});
        jNoEncontrados.setModel(modelo);
    }
    public void LimpiarTabla()
    {
        arrayListExpedientes.clear();
        arrayListInstrumentos.clear();
        System.out.println("No de cosas a eliminar " + jNoEncontrados.getRowCount());
           for (int i = 0; i < jNoEncontrados.getRowCount(); i++) 
           {
               modelo.removeRow(i);
               i-=1;
           }
    }
    private void cargarEstados()
    {
        String[] tipos = {"-Seleccionar-", "Número de expediente", "Instrumento"};
        modeloVerificar = new DefaultComboBoxModel(tipos);
        jVerificar.setModel(modeloVerificar);
        jBuscar.setEnabled(false);
    }
    
    private void NoCaracteres(JTextField a, int b)
    {
        int numerocaracteres = b;
        a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)
        {
            if(a.getText().length()>=numerocaracteres)
            {
                getToolkit().beep();
                e.consume();
                JOptionPane.showMessageDialog(null, "Has llegado al limite de caracteres de " + b);
            }
        }
        });
    }
    private void SNumeros(JTextField a)
    {
        a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)
        {
            char c=e.getKeyChar();
            if(Character.isLetter(c))
            {
                getToolkit().beep();
                e.consume();
            }
        }
        });
    }
    
        private void ValidarSolonumeros(JTextField a)
    {   
        a.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)
        {
            String cambio;
            String nuestrotexto = a.getText();
            cambio = nuestrotexto.replaceAll("[^0-9]", "");
            nuestrotexto = cambio;
            a.setText(nuestrotexto);
        }
        });       
    }   
    /**
     * Creates new form Consecutivos
     */
    public Consecutivos() 
    {
        initComponents();
        cargarEstados();
        PropiedadTabla();
        setLocationRelativeTo(null);
        SNumeros(incial);
        SNumeros(Final);
        ValidarSolonumeros(incial);
        ValidarSolonumeros(Final);
//        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLInstrucciones = new javax.swing.JLabel();
        Vista = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        jLTitulo1 = new javax.swing.JLabel();
        jLTitulo2 = new javax.swing.JLabel();
        jLNotaria = new javax.swing.JLabel();
        jLIndicaciones1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        incial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Final = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jVerificar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNoEncontrados = new javax.swing.JTable();
        jBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Analizador");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLInstrucciones.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLInstrucciones.setText("Selecciona el verificar e inserta el número incial y el final para buscar.");

        Vista.setBackground(new java.awt.Color(27, 107, 215));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/revisado.png"))); // NOI18N

        jLTitulo1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo1.setText("Verificación");

        jLTitulo2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setText("de consecutivos");

        jLNotaria.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLNotaria.setForeground(new java.awt.Color(255, 255, 255));
        jLNotaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logo21blanco.png"))); // NOI18N
        jLNotaria.setText(" Notaría");

        javax.swing.GroupLayout VistaLayout = new javax.swing.GroupLayout(Vista);
        Vista.setLayout(VistaLayout);
        VistaLayout.setHorizontalGroup(
            VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icono)
                    .addGroup(VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLNotaria)
                        .addComponent(jLTitulo1)
                        .addComponent(jLTitulo2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        VistaLayout.setVerticalGroup(
            VistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitulo2)
                .addGap(50, 50, 50)
                .addComponent(Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLNotaria)
                .addContainerGap())
        );

        jLIndicaciones1.setText("Si algún número falta entre el no. inicial y el no. final, aparecera en la tabla.");

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel2.setText("No. inicial: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incial)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel1.setText("No. final:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jVerificar.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jVerificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jVerificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jVerificarItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel3.setText("Verificar por: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVerificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jNoEncontrados.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jNoEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jNoEncontrados.setSelectionBackground(new java.awt.Color(41, 168, 73));
        jScrollPane1.setViewportView(jNoEncontrados);

        jBuscar.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(0, 153, 51));
        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Leelawadee", 0, 16)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Vista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLInstrucciones)
                            .addComponent(jLIndicaciones1))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBuscar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLInstrucciones)
                .addGap(18, 18, 18)
                .addComponent(jLIndicaciones1)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        int seleccionado = jVerificar.getSelectedIndex();
        String buscarPor=jVerificar.getItemAt(seleccionado);
        
        if(incial.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Tienes que llenar el campo incial");
        }else if(Final.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Tienes que llenar el campo final");
        }else
        {
            if(buscarPor.equals("Número de expediente"))
            {
                LimpiarTabla();
                BuscarPorExpediente();
            }else
            {
                LimpiarTabla();
                BuscarPorInstrumento();
            }
        }
    }//GEN-LAST:event_jBuscarActionPerformed
    private void BuscarPorInstrumento()
    {
        int noInicial = Integer.parseInt(incial.getText());
        int noFinal = Integer.parseInt(Final.getText());
        JalarDatosInstrumento(noInicial, noFinal);
        JalarDatosInstrumento1(noInicial, noFinal);
                for (int i = noInicial; i <= noFinal; i++) 
                {
                    if(!arrayListInstrumentos.contains(i))
                     {
                         modelo.addRow(new Object[]{i});
                     }
                }
    }
    private void BuscarPorExpediente()
    {
        int noInicial = Integer.parseInt(incial.getText());
        int noFinal = Integer.parseInt(Final.getText());
        
        JalarDatosExpediente(noInicial, noFinal);
                for (int i = noInicial; i <= noFinal; i++) 
                {
                    if(!arrayListExpedientes.contains(i))
                     {
                         modelo.addRow(new Object[]{i});
                     }
                }
    }
    public void JalarDatosInstrumento(int noInicial, int noFinal)
    {
        ConexionMySql mysql = new ConexionMySql();
        Connection cn = mysql.getConection();
        String sSQL="SELECT Instrumento FROM compraventa WHERE Instrumento >='" + noInicial + "' AND Instrumento <='" + noFinal + "' ORDER BY Instrumento";
        try 
        {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sSQL);
                while(rs.next()) 
                {
                        arrayListInstrumentos.add(rs.getInt("Instrumento"));
                }
        }catch (SQLException ex) {
                System.out.println("Error al obtener todos los expedientes" + ex);
        }finally
            //Cuando se termine todo el proceso cierra la conexión y manda llamar al metodo Inicio.
        {
                mysql.desconectar();
        }
    }
    public void JalarDatosInstrumento1(int noInicial, int noFinal)
    {
        ConexionMySql mysql = new ConexionMySql();
        Connection cn = mysql.getConection();
        String sSQL="SELECT Instrumento FROM donacion WHERE Instrumento >='" + noInicial + "' AND Instrumento <='" + noFinal + "' ORDER BY Instrumento";
        try 
        {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sSQL);
                while(rs.next()) 
                {
                        arrayListInstrumentos.add(rs.getInt("Instrumento"));
                }
        }catch (SQLException ex) {
                System.out.println("Error al obtener todos los expedientes" + ex);
        }finally
            //Cuando se termine todo el proceso cierra la conexión y manda llamar al metodo Inicio.
        {
                mysql.desconectar();
        }
    }
    public void JalarDatosExpediente(int noInicial, int noFinal)
    {
        ConexionMySql mysql = new ConexionMySql();
        Connection cn = mysql.getConection();
        String sSQL="SELECT IDNoExpediente FROM casoscliente WHERE IDNoExpediente >='" + noInicial + "' AND IDNoExpediente <='" + noFinal + "' ORDER BY IDNoExpediente";
        try 
        {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sSQL);
                while(rs.next()) 
                {
                        arrayListExpedientes.add(rs.getInt("IDNoExpediente"));
                }   
                
        }catch (SQLException ex) {
                System.out.println("Error al obtener todos los expedientes" + ex);
        }finally
            //Cuando se termine todo el proceso cierra la conexión y manda llamar al metodo Inicio.
        {
                mysql.desconectar();
        }
    }
    
    private void jVerificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jVerificarItemStateChanged
        int seleccion = jVerificar.getSelectedIndex();
        if(seleccion >= 1)
        {
            jBuscar.setEnabled(true);
        }else
        {
            jBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_jVerificarItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LimpiarTabla();
        jVerificar.setSelectedIndex(0);
        incial.setText("");
        Final.setText("");
        jBuscar.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consecutivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consecutivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consecutivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consecutivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consecutivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Final;
    private javax.swing.JLabel Icono;
    private javax.swing.JPanel Vista;
    private javax.swing.JTextField incial;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLIndicaciones1;
    private javax.swing.JLabel jLInstrucciones;
    private javax.swing.JLabel jLNotaria;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jNoEncontrados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jVerificar;
    // End of variables declaration//GEN-END:variables
}
